### ISSUE TITLE
Binlog not sending delete row event?

### ISSUE THREAD

**Issue by ii64** [JackShadow/go-binlog-example#1]
Hi, It's nice to see this example is working on my machine, but somehow why i dont receive for DeleteAction? Is something misconfigured? 
![image](https://user-images.githubusercontent.com/26342994/57082766-99037600-6d21-11e9-8862-63e93bb57841.png)
and this blocked code is not working anyway :/
![image](https://user-images.githubusercontent.com/26342994/57082827-b7697180-6d21-11e9-8d5f-6c5a1c6c0951.png)

**Comment by JackShadow** [comment]
Hello, I've updated the example. The reason was in 
`	switch e.Action {
	case canal.DeleteAction:
		return nil
	}` 
because I did not cover "deleting case" in article and it was skipped.

**Comment by ii64** [comment]
Ah didn't notice the `return` there, Thank you anw.
Have a good day 😃
